# -*- coding: utf-8 -*-
"""Stock China.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GeTe-t1uOs1cNKNOKzEtFNs0c65tf-Rh
"""

!pip install yfinance
!pip install yahoofinancials
!pip install matplotlib
!pip install numpy

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import yfinance as yf
from yahoofinancials import YahooFinancials
import datetime as dt
import numpy as np
# %matplotlib inline

end = dt.datetime.now()
aapl_df = yf.download('BABA', 
                      start='2022-03-01', 
                      end=end, 
                      progress=False,
)
aapl_df.tail()

end = dt.datetime.now()
stocks=['BABA','BIDU','002594.SZ','300750.SZ','SAIC','0981.HK','TCEHY','2330.TW','WB','XIACF','000063.SZ']
dfs = yf.download(stocks, start='2022-03-01', 
                      end=end, 
                      progress=False,
)
dfs.tail()

dfs.tail(2)['Close'].round(2)

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
# %matplotlib inline

dft=pd.read_csv('https://raw.githubusercontent.com/DONGDEVTH/stock/main/datastockchina.csv')

dft.style.set_properties(subset=['000063.SZ','002594.SZ','0981.HK','2330.TW','300750.SZ','BABA','BIDU','SAIC','TCEHY','WB','XIACF','TARGET'], **{'text-align': 'right'})

pd.set_option('colheader_justify', 'center')
dft

display(dfs.tail(2)['Close'].round(2), dft)

df4 = pd.DataFrame(dfs.tail(2)['Close'].round(2))
df4

from IPython.display import display
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

df4 = pd.DataFrame(dfs.tail(2)['Close'].round(2))

dfx = pd.concat([df4,dft], axis=0)
pd.set_option('colheader_justify', 'center')
dfx

def color_negative_red(val):
    color = 'red' if val < 100 else 'black'
    return 'color: %s' % color

dfx.style.applymap(color_negative_red)

dfx.style.set_properties(**{'background-color': 'black',
                           'color': 'green'})
dfx
dfx.mean()
dfx.to_excel("STOCK_CHINA_INFO.xlsx")

ticker = yf.Ticker('000063.SZ')
AAPL_df = ticker.history(period="5y")
AAPL_df['Close'].plot(title="000063.SZ")
AAPL_df['Close'].plot(title="000063.SZ ZTE").get_figure().savefig('ZTE')

ticker = yf.Ticker('002594.SZ')
KO_df = ticker.history(period="5y")
KO_df['Close'].plot(title="002594.SZ")
KO_df['Close'].plot(title="002594.SZ  BYD").get_figure().savefig('BYD')

ticker = yf.Ticker('0981.HK')
AMZN_df = ticker.history(period="5y")
AMZN_df['Close'].plot(title="0981.HK")
AMZN_df['Close'].plot(title="0981.HK SMIC").get_figure().savefig('SMIC')

ticker = yf.Ticker('2330.TW')
BA_df = ticker.history(period="5y")
BA_df['Close'].plot(title="2330.TW")
BA_df['Close'].plot(title="2330.TW TSMC").get_figure().savefig('TSMC')

ticker = yf.Ticker('300750.SZ')
FB_df = ticker.history(period="5y")
FB_df['Close'].plot(title="300750.SZ")
FB_df['Close'].plot(title="300750.SZ CATL").get_figure().savefig('CATL')

ticker = yf.Ticker('BABA')
GOOG_df = ticker.history(period="5y")
GOOG_df['Close'].plot(title="BABA")
GOOG_df['Close'].plot(title="BABA").get_figure().savefig('BABA')

ticker = yf.Ticker('BIDU')
GOOG_df = ticker.history(period="5y")
GOOG_df['Close'].plot(title="BIDU")
GOOG_df['Close'].plot(title="BIDU").get_figure().savefig('BIDU')

ticker = yf.Ticker('SAIC')
KO_df = ticker.history(period="5y")
KO_df['Close'].plot(title="SAIC")
KO_df['Close'].plot(title="SAIC").get_figure().savefig('SAIC')

ticker = yf.Ticker('TCEHY')
MSFT_df = ticker.history(period="5y")
MSFT_df['Close'].plot(title="TCEHY")
MSFT_df['Close'].plot(title="TCEHY").get_figure().savefig('TCEHY')

ticker = yf.Ticker('WB')
MSFT_df = ticker.history(period="5y")
MSFT_df['Close'].plot(title="WB")
MSFT_df['Close'].plot(title="WB").get_figure().savefig('WB')

ticker = yf.Ticker('XIACF')
MSFT_df = ticker.history(period="5y")
MSFT_df['Close'].plot(title="XIACF")
MSFT_df['Close'].plot(title="XIACF").get_figure().savefig('XIACF')

import matplotlib.pyplot as plt

from PIL import Image

image1 = Image.open(r"ZTE.png")
image2 = Image.open(r"SMIC.png")
image3 = Image.open(r"TSMC.png")
image4 = Image.open(r"CATL.png")
image5 = Image.open(r"BABA.png")
image6 = Image.open(r"BIDU.png")
image7 = Image.open(r"BYD.png")
image8 = Image.open(r"SAIC.png")
image9 = Image.open(r"TCEHY.png")
image10 = Image.open(r"WB.png")
image11 = Image.open(r"XIACF.png")


im1 = image1.convert("RGB")
im2 = image2.convert("RGB")
im3 = image3.convert("RGB")
im4 = image4.convert("RGB")
im5 = image5.convert("RGB")
im6 = image6.convert("RGB")
im7 = image7.convert("RGB")
im8 = image8.convert("RGB")
im9 = image9.convert("RGB")
im10 = image10.convert("RGB")
im11 = image11.convert("RGB")


imagelist = [im2,im3,im4,im5,im6,im7,im8,im9,im10,im11]
im1.save(r"STOCK_CHINA.pdf",save_all=True, 
append_images=imagelist)

import smtplib
import mimetypes
from email.mime.multipart import MIMEMultipart
from email import encoders
from email.message import Message
from email.mime.audio import MIMEAudio
from email.mime.base import MIMEBase
from email.mime.image import MIMEImage
from email.mime.text import MIMEText


emailfrom = ""
emailto = ['', '', '', '', '', '']
#emailtocc = ""
#emailtocc = ""
fileToSend = "STOCK_CHINA_INFO.xlsx"
fileToSend2 = "STOCK_CHINA.pdf"
username = ""
password = ""

msg = MIMEMultipart()
msg["From"] = emailfrom
msg['To'] = ", ".join(emailto)
#msg["Cc"] = emailtocc
msg["Subject"] = "Stock China! (-v-) "
msg.preamble = "Stock China! (-v-)"

#EXCEL FILE
ctype, encoding = mimetypes.guess_type(fileToSend)
if ctype is None or encoding is not None:
    ctype = "application/octet-stream"

maintype, subtype = ctype.split("/", 1)

if maintype == "text":
    fp = open(fileToSend)
    # Note: we should handle calculating the charset
    attachment = MIMEText(fp.read(), _subtype=subtype)
    fp.close()
elif maintype == "image":
    fp = open(fileToSend, "rb")
    attachment = MIMEImage(fp.read(), _subtype=subtype)
    fp.close()
elif maintype == "audio":
    fp = open(fileToSend, "rb")
    attachment = MIMEAudio(fp.read(), _subtype=subtype)
    fp.close()
elif maintype == "pdf":
    fp = open(fileToSend, "rb")
    attachment = MIMEAudio(fp.read(), _subtype=subtype)
    fp.close()
elif maintype == "xlsx":
    fp = open(fileToSend, "rb")
    attachment = MIMEAudio(fp.read(), _subtype=subtype)
    fp.close()
else:
    fp = open(fileToSend, "rb")
    attachment = MIMEBase(maintype, subtype)
    attachment.set_payload(fp.read())
    fp.close()
    encoders.encode_base64(attachment)
attachment.add_header("Content-Disposition", "attachment", filename=fileToSend)
msg.attach(attachment)

#PICTURE FILE
ctype, encoding = mimetypes.guess_type(fileToSend2)
if ctype is None or encoding is not None:
    ctype = "application/octet-stream"

maintype, subtype = ctype.split("/", 1)

if maintype == "text":
    fp = open(fileToSend2)
    # Note: we should handle calculating the charset
    attachment = MIMEText(fp.read(), _subtype=subtype)
    fp.close()
elif maintype == "image":
    fp = open(fileToSend2, "rb")
    attachment = MIMEImage(fp.read(), _subtype=subtype)
    fp.close()
elif maintype == "audio":
    fp = open(fileToSend2, "rb")
    attachment = MIMEAudio(fp.read(), _subtype=subtype)
    fp.close()
elif maintype == "pdf":
    fp = open(fileToSend2, "rb")
    attachment = MIMEAudio(fp.read(), _subtype=subtype)
    fp.close()
elif maintype == "xlsx":
    fp = open(fileToSend2, "rb")
    attachment = MIMEAudio(fp.read(), _subtype=subtype)
    fp.close()
else:
    fp = open(fileToSend2, "rb")
    attachment = MIMEBase(maintype, subtype)
    attachment.set_payload(fp.read())
    fp.close()
    encoders.encode_base64(attachment)
attachment.add_header("Content-Disposition", "attachment", filename=fileToSend2)
msg.attach(attachment)

server = smtplib.SMTP("smtp.gmail.com:587")
server.starttls()
server.login(username,password)
server.sendmail(emailfrom, emailto, msg.as_string())
server.quit()